### ISSUE TITLE
Upload CSV of Keywords

### ISSUE THREAD

**Issue by sethsandaru** [sethsandaru/cross-z#1]
## Requirements
- Authenticated users can upload a CSV file of keywords. This upload file can be in any size from 1 to 100 keywords.
- Create a user interface to perform this action.
- Optional: create an API endpoint to perform this action.

**Comment by sethsandaru** [comment]
## To-Do List
- [ ] Build up the core
- [ ] Build up the base frontend
- [ ] Dashboard view
- [ ] Upload CSV Frontend
- [ ] Upload CSV RestAPI
- [ ] Process CSV RestAPI

**Comment by sethsandaru** [comment]
- Final Link URL: https://<domain>/upload-csv
